modLoader = "javafml"
loaderVersion = "[47,)"
license = "https://github.com/${repository}/blob/1.19.x/LICENSE.txt"
issueTrackerURL = "https://github.com/${repository}/issues"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_author}"
description = '''Upgrade your backtank and utilize the pressurized air to fly'''

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "create"
mandatory = true
versionRange = "[0.5.1.c,)"
ordering = "NONE"
side = "BOTH"
